version: '2'

services:
    web:
        build: .
        environment:
            - FLASK_APP=flaskr
            - FLASK_ENV=development
        depends_on:
            - redis
        network_mode: host

    redis:
        image: redis:5.0-alpine

    sqlite:
        image: keinos/sqlite3