version: '2.2'

services:
  web:
    build: .
    environment:
      - FLASK_APP=toto
      - FLASK_ENV=development
      - SECRET_KEY=abc123
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web: