version: '2'

services:
    web:
        build: .
        environment:
            - FLASK_APP=flaskr
            - FLASK_ENV=development
            - REDIS_URL=redis://:@redis:6379/0
        depends_on:
            - redis
        volumes:
            - .:/code
        ports:
        - 5000:5000

    redis:
        image: redis:5.0-alpine
